# Explicit build settings for Netlify
[build]
  # This tells Netlify where to find the site's files to publish.
  # "." means the root directory.
  publish = "."

  # This explicitly tells Netlify where the functions are.
  functions = "functions/"

# This is a fallback rule to ensure the site works correctly
